services:
    _defaults:
        public: true

    coreshop.context.currency:
        alias: CoreShop\Component\Currency\Context\CurrencyContextInterface
        deprecated: { package: "coreshop/currency-bundle", version: "3.0", message: 'The "%alias_id%" service alias is deprecated since CoreShop 3.0 and will be removed with 3.1, use CoreShop\Component\Currency\Context\CurrencyContextInterface instead' }

    coreshop.currency_converter:
        alias: CoreShop\Component\Currency\Converter\CurrencyConverterInterface
        deprecated: { package: "coreshop/currency-bundle", version: "3.0", message: 'The "%alias_id%" service alias is deprecated since CoreShop 3.0 and will be removed with 3.1, use CoreShop\Component\Currency\Converter\CurrencyConverterInterface instead' }

    coreshop.context.currency.cached:
        alias: CoreShop\Component\Currency\Context\CachedCurrencyContext
        deprecated: { package: "coreshop/currency-bundle", version: "3.0", message: 'The "%alias_id%" service alias is deprecated since CoreShop 3.0 and will be removed with 3.1, use CoreShop\Component\Currency\Context\CachedCurrencyContext instead' }

    coreshop.context.currency.fixed:
        alias: CoreShop\Component\Currency\Context\FixedCurrencyContext
        deprecated: { package: "coreshop/currency-bundle", version: "3.0", message: 'The "%alias_id%" service alias is deprecated since CoreShop 3.0 and will be removed with 3.1, use CoreShop\Component\Currency\Context\FixedCurrencyContext instead' }
